---

- name: Gather facts on listening ports
  listen_ports_facts:

- name: Ensure that the port is free
  fail: 
    msg: "Port {{ web_app_port_host }} is busy"
  when: "web_app_port_host in ((ansible_facts.tcp_listen + ansible_facts.udp_listen) | map(attribute='port') | unique)"

- name: Apply docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ web_app_deploy_dir }}/docker-compose.yml"

- name: Create and start services
  community.docker.docker_compose:
    project_src: "{{ web_app_deploy_dir }}"
    state: present
    pull: true
  register: output

- name: Show results
  debug:
    var: output
 