---

- hosts: 127.0.0.1
  become: true
  roles:
    - "web_app"
  vars:
    web_app_name: app_python
    web_app_port_host: 3000
    web_app_port_docker: 8000
  vars_files:
    - ../../../group_vars/all.yml