# Remove secrets.yml from .helmignore if you want to use this secret
apiVersion: v1
kind: Secret
metadata:
  name: secret
  labels:
    app: app
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  secret: "{{ .Values.secret | b64enc | quote }}"
  